### ISSUE TITLE
Maybe use Type 1 fonts intead of Type 3 fonts

### ISSUE THREAD

**Issue by foxik** [D-iii-S/admin-forms#3]
Currently bitmap Type 3 fonts are used in the generated PDF (at least on Texlive 2018 on Debian Buster), which makes rendering quite slow.

I believe Type 1 fonts would increase experience -- I used
```tex
\usepackage{lmodern}
```
to use them.

**Comment by ceresek** [comment]
Thanks for the tip, fixed in 637606137bde9b499ee63001deb1dcafffe3cbb3.
